app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redis;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// initial page
Route::get('/', 'Auth\AuthController@showLoginForm');

// authentication page
Route::auth();

// view home
Route::get('/home', [
    'as' => 'home',
    'uses' => 'HomeController@showHome',
]);

Route::get('message', [
    'as' => 'message',
    'uses' => 'HomeController@showMessage',
]);

Route::get('info/decompose','\Lubusin\Decomposer\Controllers\DecomposerController@index');

Route::get('info/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Site.php
<?php

namespace IhrV2\Models;

use Illuminate\Database\Eloquent\Model;

class Site extends Model {

    protected $table = 'sites';

    // public $timestamps = false;

    protected $fillable = [
        'code',
        'name',
        'full_name',
        'tm_name',
        'both_name',
        'old_name',
        'phase_id',
        'region_id',
        'street1',
        'street2',
        'postal_code',
        'city',
        'district',
        'state_id',
        'address_label',
        'email',
        'website',
        'latitude',
        'longitude',
        'start',
        'end',
        'bandwidth',
        'backhaul',
        'location_id',
        'status',
        'date_modified',
        'created_at',
        'updated_at'
    ];

    public function UserJobActive() {
        return $this->hasMany('IhrV2\Models\UserJob', 'sitecode', 'code')->where('status', 1);
    }

    // user job active/inactive & position m/am
    // ----------------------------------------
    public function UserJobSite() {
        return $this->hasMany('IhrV2\Models\UserJob', 'sitecode', 'code')->where('flag', 1)->whereIn('position_id', array(4,5));
    }

    // public function UserJobActive2() {
    //     return $this->hasMany('IhrV2\Models\UserJob', 'sitecode', 'code')->where('flag', 1);
    // }

    public function PhaseName() {
        return $this->belongsTo('IhrV2\Models\Phase', 'phase_id');
    }

    public function StateName() {
        return $this->belongsTo('IhrV2\Models\State', 'state_id', 'code');
    }

    public function RegionName() {
        return $this->belongsTo('IhrV2\Models\Region', 'region_id');
    }

    public function RegionManager() {
        return $this->belongsTo('IhrV2\Models\RegionUser', 'region_id', 'region_id');
    }

    public function StatusName() {
        return $this->belongsTo('IhrV2\Models\Status', 'status');
    }

    // get region manager id
    // ---------------------
    public function RegionManagerInfo() {
        return $this->hasOne('IhrV2\Models\RegionUser', 'region_id', 'region_id');
    }

    public function getAvailabilityAttribute() {

        if (!empty($this->status)) {

            // status active
            // -------------
            if ($this->status == 1) {
                return '<span class="text-primary">' . strtoupper($this->StatusName->name) . '</span>';
            }

            // status inactive
            // ---------------
            else if ($this->status == 2) {
                return '<span class="text-danger">' . strtoupper($this->StatusName->name) . '</span>';
            }

            // status unknown
            // --------------
            else {
                return '<span class="text-default">Unknown</span>';
            }
        }

        // status null
        // -----------
        else {
            return '-';
        }

    }

    public function scopeOfSort($query, $sort) {
        foreach ($sort as $column => $direction) {
            $query->orderBy($column, $direction);
        }
        return $query;
    }

}

app/User.php
<?php

namespace IhrV2;

use Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

// use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable {
    
    // public $timestamps = false;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'username',
        'name',
        'staff_id',
        'prev_staff_id',
        'email',
        'password',
        'api_token',
        'group_id',
        'is_admin',
        'icno',
        'permanent_street_1',
        'permanent_street_2',
        'permanent_postcode',
        'permanent_city',
        'permanent_state',
        'correspondence_street_1',
        'correspondence_street_2',
        'correspondence_postcode',
        'correspondence_city',
        'correspondence_state',
        'telno1',
        'telno2',
        'hpno',
        'hpno2',
        'faxno',
        'website',
        'personal_email',
        'work_email',
        'gender_id',
        'marital_id',
        'height',
        'weight',
        'dob',
        'pob',
        'nationality_id',
        'race_id',
        'religion_id',
        'partner_name',
        'partner_phone',
        'child_no',
        'sitecode',
        'itaxno',
        'epfno',
        'socsono',
        'bankname',
        'bankno',
        'status',
        'remember_token',
        'sid',
        'action_date',
        'last_login',
        'date_created',
        'date_modified',
        'imei',
        'device',
        'edit',
        'mobile',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token', 'api_token'
    ];

    // public function roles()
    // {
    //     return $this->belongsToMany(Role::class);
    // }

    // public function hasRole($role) //
    // {
    //     if (is_string($role)) {
    //         return $this->roles->contains('name', $role);
    //     }
    //     return !! $role->intersect($this->roles)->count();
    // }

    // public function assign($role)
    // {
    //     if (is_string($role)) {
    //         return $this->roles()->save(
    //             Role::whereName($role)->firstOrFail()
    //         );
    //     }
    //     return $this->roles()->save($role);
    // }

    /**
     * Always hash the password when we save it to the database
     */
    // public function setPasswordAttribute($value) {
    //     $this->attributes['password'] = Hash::make($value);
    // }

    // always encrypt value password when user enter the password
    // public function setPasswordAttribute($value)
    // {
    //     $this->attributes['password'] = bcrypt($value);
    // }

    public function getEmailForPasswordReset() {
        return $this->personal_email;
    }

    public function scopeIsActive($q) {
        $q->where('status', 1);
    }

    public function scopeIsActiveAndIDDesc($q) {
        $q->where('status', 1)->orderBy('id', 'DESC');
    }

    // belongs to
    // ----------
    public function GroupName() {
        return $this->belongsTo('IhrV2\Models\Group', 'group_id');
    }

    public function GenderName() {
        return $this->belongsTo('IhrV2\Models\Gender', 'gender_id');
    }

    public function MaritalName() {
        return $this->belongsTo('IhrV2\Models\MaritalStatus', 'marital_id');
    }

    public function RaceName() {
        return $this->belongsTo('IhrV2\Models\Race', 'race_id');
    }

    public function ReligionName() {
        return $this->belongsTo('IhrV2\Models\Religion', 'religion_id');
    }

    public function NationalityName() {
        return $this->belongsTo('IhrV2\Models\Nationality', 'nationality_id');
    }

    public function SiteNameInfo() {
        return $this->belongsTo('IhrV2\Models\Site', 'sitecode', 'code');
    }

    public function StatusName() {
        return $this->belongsTo('IhrV2\Models\UserStatus', 'status');
    }

    // has one
    // -------
    public function UserLatestJob() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLatestJob2() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 1);
    }

    public function UserCurrentJob() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->orderBy('id', 'desc');
    }

    public function UserCurrentJob2() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('flag', 1);
    }

    public function UserCurrentContract2() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('flag', 1);
    }    

    public function UserLatestContract() {
        // return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1);
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLatestContract2() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLastContract() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->orderBy('id', 'desc');
    }

    public function UserInactive() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2);
    }

    // inactive job & contract
    // -----------------------
    public function UserInactiveJob() {
        // return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2);
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2)->where('flag', 1);
    }

    public function UserInactiveContract() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 2)->where('flag', 1);
    }

    // user photo
    // ----------
    public function UserPhotoActive() {
        return $this->hasOne('IhrV2\Models\UserPhoto', 'user_id')->where('active', 1);
    }

    public function UserPhotoApproved() {
        return $this->hasOne('IhrV2\Models\UserPhotoHistory', 'user_id')->where('status', 2)->where('flag', 1);
    }

    // has many
    // --------
    public function UserJob() {
        return $this->hasMany('IhrV2\Models\UserJob', 'user_id');
    }

    public function UserContract() {
        return $this->hasMany('IhrV2\Models\UserContract', 'user_id');
    }

    public function UserEducation() {
        return $this->hasMany('IhrV2\Models\UserEducation', 'user_id')->orderBy('id', 'DESC');
    }

    public function UserEducationOne() {
        return $this->hasOne('IhrV2\Models\UserEducation', 'user_id')->orderBy('id', 'DESC');
    }

    public function UserEmergency() {
        return $this->hasMany('IhrV2\Models\UserEmergency', 'user_id')->orderBy('id', 'DESC');
    }

    // display status color
    // --------------------
    public function getStatusColorAttribute() {
        if ($this->status == 1) {
            return '<span class="text-primary">' . strtoupper($this->StatusName->name) . '</span>';
        } else {
            return '<span class="text-danger">' . strtoupper($this->StatusName->name) . '</span>';
        }
    }

}

resources/views/modules/user/tab/contract.blade.php
<!-- contract -->
<div class="tab-pane" id="contract">

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 class="panel-title">Contract</h4>
				</div>
				<div class="panel-body nopadding">

					<div class="row col-wrap">			
						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">

									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-success">
												<td colspan="2"><i class="icon-note"></i>&nbsp;<strong>Current Contract</strong></td>
											</tr>
										</thead>
										@if (!empty($contract))
											<tr>
												<td>Status</td>
												<td>
													{!! $contract->status_contract !!}
												</td>
											</tr>
											<tr>
												<td class="col-md-4">Contract Date</td>
												<td class="col-md-8">
													@if ($contract->date_from != '0000-00-00')
														{{ \Carbon\Carbon::parse($contract->date_from)->format('j M Y') }}
													@else
														{{ $contract->date_from }}
													@endif
													 - 
													@if ($contract->date_to != '0000-00-00')
														{{ \Carbon\Carbon::parse($contract->date_to)->format('j M Y') }}
													@else
														{{ $contract->date_to }}
													@endif	
													<i class="fa fa-check-circle text-success" title="Current Contract"></i>														
												</td>
											</tr>
											<tr>
												<td>Days</td>
												<td>{!! $contract->duration !!}</td>
											</tr>
											<tr>
												<td>Remaining Days</td>
												<td>{!! $contract->remain_day !!}</td>
											</tr>
											<tr>
												<td>Site Name</td>
												<td>{{ $contract->sitecode }} {{ $contract->SiteName->name }}</td>
											</tr>
											<tr>
												<td>Entitled AL</td>
												<td>{{ $entitled }}</td>
											</tr>
											<tr>
												<td>Leave Taken AL</td>
												<td>
													@if ($taken)
														{{ round($taken->total, 1) }}
													@else
														{{ '-' }}
													@endif
												</td>
											</tr>
										@else
											<tr>
												<td colspan="2">No record</td>
											</tr>
										@endif
									</table>

									@if (count($duplicate) > 1)
										<?php $no_d = 0; ?>
										{{ Form::open(array('class' => 'form-horizontal', 'role' => 'form')) }}
											<table class="table table-condensed table-responsive">
												<thead>
													<tr class="bg-danger">
														<td colspan="5"><i class="icon-docs"></i>&nbsp;<strong>Active Contract</strong></td>
													</tr>
												</thead>
												<tr class="active">
													<th class="col-md-1">No</th>
													<th class="col-md-3">Site Code</th>
													<th class="col-md-3">Start</th>
													<th class="col-md-3">End</th>
													<th class="col-md-2 text-right">Actions</th>
												</tr>
												@foreach ($duplicate as $d)
													<?php $no_d++; ?>
													<tr>
														<td>{{ $no_d }}</td>
														<td>{{ $d->sitecode }}</td>
														<td>
															@if ($d->date_from != '0000-00-00')
																{{ \Carbon\Carbon::parse($d->date_from)->format('j M Y') }}
															@else
																{{ $d->date_from }}
															@endif															
														</td>
														<td>
															@if ($d->date_to != '0000-00-00')
																{{ \Carbon\Carbon::parse($d->date_to)->format('j M Y') }}
															@else
																{{ $d->date_to }}
															@endif															
														</td>
														<td class="text-right">{{ Form::radio('duplicate_id', $d->id) }}</td>
													</tr>
												@endforeach
												<tr><td colspan="5">Note: Found <strong>{{ $no_d }}</strong> Active Contract. Please confirm the Current Contract.</td></tr>
												<tr><td colspan="5" class="text-right"><button type="button" class="btn btn-sm btn-danger btn_click" id="set" title="Set Default"><i class="icon-check"></i>&nbsp;Set</button></td></tr>										
											</table>
										{{ Form::close() }}
									@endif

								</div>
							</div>
						</div>

						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">
									<div id="table-prev"></div>	
								</div>
							</div>
						</div>
					</div>


					<div class="row col-wrap">			
						<div class="col-sm-12 col">
							<div class="row">
								<div class="col-md-12">

									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-info">
												<td colspan="5" class="text-center"><i class="icon-exclamation"></i>&nbsp;<strong>Diciplinary Record</strong></td>
											</tr>
										</thead>										
										<tr class="active">
											<th class="col-md-1">No</th>
											<th class="col-md-3">Letter Date /<br>Letter Name</th>
											<th class="col-md-4">Apply Date /<br>Upload By</th>
											<th class="col-md-2">Reminder /<br>Status</th>
											<th class="col-md-2 text-right">Actions</th>
										</tr>
										@if (count($letter) > 0)
											<?php $no = 0; ?>
											@foreach ($letter as $i)
												<?php $no++; ?>
												<tr>
													<td>{{ $no }}</td>
													<td>
														{{ $i->letter_date }} /<br>
														@if (!empty($i->LetterTypeName))
															{{ $i->LetterTypeName->name }}
														@else
															{{ '-' }}
														@endif
													</td>
													<td>
														{{ $i->action_date }} /<br>
														@if (!empty($i->LetterActionBy))
															{{ $i->LetterActionBy->name }}
														@else
															{{ '-' }}
														@endif
													</td>
													<td>
														{{ CommonHelper::ordinal($i->reminder_no) }} /<br>
														{!! $i->availability !!}
													</td>
													<td class="text-right">
														@if (!empty($i->LetterAttachment))
															<?php
																$attachment = $i->LetterAttachment->filename.'.'.$i->LetterAttachment->ext;
															?> 													
															<a href="#" data-url="{{ route('mod.user.view.popup.letter', array($i->id)) }}" id="modal-popup" class="btn btn-primary btn-sm" title="View Letter"><i class="icon-magnifier-add"></i></a>&nbsp;<a href="{{ route('lib.file.letter', array($attachment)) }}" target="_blank" title="Attachment" class="btn btn-primary btn-sm"><i class="icon-paper-clip"></i></a>
														@else
															<a href="#" class="btn btn-success btn-sm" title="View Details"><i class="icon-magnifier-add"></i></a>
														@endif											
													</td>
												</tr>
											@endforeach
											<tr>
												<td colspan="5" class="text-center">Total: {{ $no }}</td>
											</tr>
										@else
											<tr>
												<td colspan="5">No record</td>
											</tr>
										@endif
									</table>
								</div>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>
	</div>
</div>





<script type="text/javascript">
	getModDataList("{{ route('mod.user.contract.prev.api', array($uid, $token)) }}", 1);
</script>

<style type="text/css">
#list a {
   color: #FFFFFF;
   text-decoration: underline;
}  
a:link {
   color: #FFFFFF;
}
a:visited {
   color: #FFFFFF;
}
a:hover {
   color: #FFFFFF;
}
.modal-dialog{
    overflow-y: initial !important
}
.modal-body{
    max-height: calc(100vh - 200px);
    overflow-y: auto;
}
</style>

resources/views/modules/user/tab/education.blade.php
<!-- education -->
<div class="tab-pane" id="education">

	<div class="row">
		<div class="col-md-12">

			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 class="panel-title">Education</h4>
				</div>	
      			
				<div class="panel-body nopadding">
					<table class="table table-condensed table-responsive">
						<thead>
							<tr class="active">
								<th>No</th>
								<th>Year From</th>
								<th>Year To</th>
								<th>Institution</th>
								<th>Result</th>
								<th class="actions text-right">Actions</th>
							</tr>
						</thead>
						@if (count($detail) > 0)
							<?php $no = 0; ?>											
							@foreach ($detail as $education)
							<?php $no++; ?>												
							<tr>
								<td>{{ $no }}</td>
								<td>
									@if ($education->year_from)
										{{ $education->year_from }}
									@else
										{{ '-' }}
									@endif
								</td>
								<td>
									@if ($education->year_to)
										{{ $education->year_to }}
									@else
										{{ '-' }}
									@endif
								</td>
								<td>
									@if ($education->name_education)
										{{ $education->name_education }}
									@else
										{{ '-' }}
									@endif
								</td>
								<td>
									@if ($education->result)
										{{ $education->result }}
									@else
										{{ '-' }}
									@endif
								</td>
								<td class="text-right">

								</td>
							</tr>
							@endforeach
						@else
							<tr><td colspan="6">No record</td></tr>
						@endif
					</table>		             
				</div>	






			</div>
		</div>
	</div>
</div>

resources/views/modules/user/tab/emergency.blade.php
<div class="tab-pane" id="emergency">

	<div class="row">
		<div class="col-md-12">

			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 class="panel-title">Emergency Contact</h4>
				</div>	
      			
				<div class="panel-body nopadding">
					<table class="table table-condensed table-responsive">
						<thead>
							<tr class="active">
								<th>No</th>
								<th>Name</th>
								<th>Relationship</th>
								<th>Address</th>
								<th>Tel No.</th>
								<th class="actions text-right">Actions</th>
							</tr>
						</thead>
						@if (count($detail) > 0)
							<?php $no = 0; ?>												
							@foreach ($detail as $i)
							<?php $no++; ?>												
							<tr>
								<td>{{ $no }}</td>
								<td>{{ $i->name }}</td>
								<td>{{ $i->relation }}</td>					           
								<td>{{ $i->address }}</td>			              
								<td>{{ $i->telno }}</td>	              
								<td class="text-right">
								</td>
							</tr>
							@endforeach
						@else
							<tr><td colspan="6">No record</td></tr>
						@endif
					</table>		             
				</div>






			</div>
		</div>
	</div>
</div>

resources/views/modules/user/tab/family.blade.php
<div class="tab-pane" id="family">

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 class="panel-title">Family</h4>
				</div>
				<div class="panel-body nopadding">


					<div class="row col-wrap">			
						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">


									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-success">
												<td colspan="2"><i class="icon-people"></i>&nbsp;<strong>Spouse</strong></td>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td class="col-md-3">Name</td>
												<td class="col-md-9">
													@if ($user->partner_name)
														{{ $user->partner_name }}
													@else
														{{ '-' }}
													@endif
												</td>
											</tr>
											<tr>
												<td>Phone</td>
												<td>
													@if ($user->partner_phone)
														{{ $user->partner_phone }}
													@else
														{{ '-' }}
													@endif													
												</td>
											</tr>
										</tbody>
									</table>


								</div>
							</div>
						</div>

						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">	
									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-warning">
												<td colspan="2"><i class="icon-emotsmile"></i>&nbsp;<strong>Children</strong></td>
											</tr>
										</thead>
										<tbody>
											<tr>
												<td>Total</td>
												<td class="text-right">
													@if ($user->child_no)
														{{ $user->child_no }}
													@else
														{{ '-' }}
													@endif
												</td>
											</tr>
										</tbody>
									</table>
								</div>
							</div>
						</div>
					</div>


				</div>
			</div>
		</div>
	</div>
</div>

resources/views/modules/user/tab/job.blade.php
<!-- job -->
<div class="tab-pane" id="job">

	<div class="row">
		<div class="col-md-12">
			<div class="panel panel-primary">
				<div class="panel-heading">
					<h4 class="panel-title">Job</h4>
				</div>
				<div class="panel-body nopadding">


					<div class="row col-wrap">			
						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">


									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-success">
												<td colspan="2"><i class="icon-briefcase"></i>&nbsp;<strong>Current Job</strong></td>
											</tr>
										</thead>
										@if ($job)
											<tr>
												<td>Status</td>
												<td>
													{!! $job->status_color !!}
												</td>
											</tr>
											<tr>
												<td class="col-md-4">Staff ID</td>
												<td class="col-md-8">{{ $job->staff_id }}</td>
											</tr>
											<tr>
												<td>Join Date</td>
												<td>{{ \Carbon\Carbon::parse($job->join_date)->format('j M Y') }}</td>
											</tr>
											<tr>
												<td>Position</td>
												<td>
													@if ($job->PositionName) 
														{{ $job->PositionName->name }} 
													@else 
														{{ '-' }} 
													@endif																										
												</td>
											</tr>

											@if ($job->UserDetail->group_id == 3)
												<tr>
													<td>Phase</td>
													<td>
														@if ($job->PhaseName)
															{{ $job->PhaseName->name }}
														@else
															{{ '-' }}
														@endif														
													</td>
												</tr>
												<tr>
													<td>Region</td>
													<td>
														@if ($job->RegionName)
															{{ $job->RegionName->name }}
														@else
															{{ '-' }}
														@endif														
													</td>
												</tr>												
											@endif

											@if (!empty($job->sitecode))
												<tr>
													<td>Site Name</td>
													<td>
														@if ($job->SiteName)
															{{ $job->SiteName->code }}&nbsp;{{ $job->SiteName->name }}
														@else
															{{ '-' }}
														@endif													
													</td>
												</tr>
											@endif
											<tr>
												<td>Resign Date</td>
												<td>
													@if ($job->resign_date && $job->resign_date != '0000-00-00')
														{{ \Carbon\Carbon::parse($job->resign_date)->format('j M Y') }}
													@else
														{{ '-' }}
													@endif
												</td>
											</tr>
										@else
											<tr>
												<td colspan="2">No record</td>
											</tr>
										@endif
									</table>


								</div>
							</div>
						</div>

						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">	
									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-danger">
												<td colspan="4"><i class="icon-clock"></i>&nbsp;<strong>{{ count($prev) }} Movement</strong></td>
											</tr>
										</thead>
										<tr class="active">
											<th class="col-md-1">No</th>
											<th class="col-md-4">Position</th>
											<th class="col-md-5">Site Name</th>
											<th class="col-md-2 text-right">Actions</th>
										</tr>										
										@if (count($prev) > 0)
											<?php $no = 0; ?>
											@foreach ($prev as $i)
												<?php $no++; ?>
												<tr>
													<td>{{ $no }}</td>
													<td>
														@if ($i->PositionName) 
															{{ $i->PositionName->name }} 
														@else 
															{{ '-' }} 
														@endif															
													</td>
													<td>
														@if ($i->SiteName)
															{{ $i->SiteName->code }}&nbsp;{{ $i->SiteName->name }}
														@else
															{{ '-' }}
														@endif															
													</td>
													<td class="text-right">
														<a href="#" data-url="{{ route('mod.user.view.popup.job', array($i->id, $i->user_id, $token)) }}" data-toggle="modal" id="list" class="btn btn-success btn-sm" title="View Details"><i class="icon-magnifier-add"></i></a>
													</td>
												</tr>
											@endforeach
										@else
											<tr>
												<td colspan="4">No record</td>
											</tr>
										@endif
									</table>
								</div>
							</div>
						</div>
					</div>


					<div class="row col-wrap">			
						<div class="col-sm-6 col">
							<div class="row">
								<div class="col-md-12">

									<table class="table table-condensed table-responsive">
										<thead>
											<tr class="bg-info">
												<td colspan="4"><i class="icon-directions"></i>&nbsp;<strong>{{ count($transfer) }} Transfer</strong></td>
											</tr>
										</thead>
										<tr class="active">
											<th class="col-md-1">No</th>
											<th class="col-md-3">Staff ID</th>
											<th class="col-md-2">Status</th>											
											<th class="col-md-6">Site Name</th>
										</tr>
										@if (count($transfer) > 0)
											<?php $no = 0; ?>
											@foreach ($transfer as $i)
												<?php $no++; ?>
												<tr>
													<td>{{ $no }}</td>
													<td>
														@if ($i->staff_id)
															<a href="{{ route('mod.user.view', array($i->id, $i->api_token)) }}" style="color:#ff7f0e">{{ $i->staff_id }}</a>
														@else
															{{ '-' }}
														@endif
													</td>
													<td>{!! $i->status_color !!}</td>
													<td>{{ $i->SiteNameInfo->code }} {{ $i->SiteNameInfo->name }}</td>
												</tr>
											@endforeach
										@else
											<tr>
												<td colspan="4">No record</td>
											</tr>
										@endif
									</table>

								</div>
							</div>
						</div>

					</div>


				</div>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
$(document).ready(function(){
   $('[data-toggle="modal"]').click(function(e) {
      e.preventDefault();
      $(".divLoading").addClass('show');
      var url = $(this).attr('data-url');
      $.get(url, function(data) {
         $(data).modal();
         $(".divLoading").removeClass('show').addClass('hide');
      });
   });
});
</script>


<style type="text/css">
#list a {
   color: #FFFFFF;
   text-decoration: underline;
}  
a:link {
   color: #FFFFFF;
}
a:visited {
   color: #FFFFFF;
}
a:hover {
   color: #FFFFFF;
}
.modal-dialog{
    overflow-y: initial !important
}
.modal-body{
    max-height: calc(100vh - 200px);
    overflow-y: auto;
}
</style>