app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redis;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// initial page
Route::get('/', 'Auth\AuthController@showLoginForm');

// authentication page
Route::auth();

// view home
Route::get('/home', [
    'as' => 'home',
    'uses' => 'HomeController@showHome',
]);

Route::get('message', [
    'as' => 'message',
    'uses' => 'HomeController@showMessage',
]);

Route::get('info/decompose','\Lubusin\Decomposer\Controllers\DecomposerController@index');

Route::get('info/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/Announcement.php
<?php

namespace IhrV2\Models;

use Illuminate\Database\Eloquent\Model;

class Announcement extends Model
{
    

	protected $table = 'announcements';


    protected $fillable = [
    	'user_id',
    	'apply_date',
    	'message',
    	'type_id',
    	'status',
    	'order'
    ];


	public function CreatedBy() {
		return $this->belongsTo('IhrV2\User', 'user_id');
	}	

    public function getAvailabilityAttribute()
    {
        if ($this->status == 1) {
            return '<span class="text-primary">ACTIVE</span>';
        }
        else if ($this->status == 2) {
            return '<span class="text-danger">CANCEL</span>';
        }
        else {
            return '<span class="text-default">UNKNOWN</span>';            
        }
    }


    public function getTypeNameAttribute()
    {
        if ($this->type_id == 1) {
            return 'Site';
        }
        else {
            return 'Admin';            
        }
    }




}

resources/views/modules/announcement/create.blade.php
@extends('layouts/backend')

@section('content')



{{ Form::open(array('class' => 'form-horizontal', 'role' => 'form')) }}
<div class="row">
	<div class="col-lg-12">

		<div class="panel panel-default">
			<div class="panel-body">
				<legend>Announcement</legend>

				<div class="form-group">
					<div class="col-md-2 required">          
						{{ Form::label('selectType', 'Type') }}   
						@if ($errors->has('type_id'))
							<p class="text-danger">{{ $errors->first('type_id') }}</p>
						@endif      
						{{ Form::select('type_id', array(1 => 'Site Supervisor', 2 => 'Admin'), old('type_id'), array('class' => 'form-control', 'id' => 'selectType')) }}                   
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-2 required">          
						{{ Form::label('selectOrder', 'Order') }}   
						@if ($errors->has('order'))
							<p class="text-danger">{{ $errors->first('order') }}</p>
						@endif      
						{{ Form::text('order', old('order'), array('class'=>'form-control', 'id' => 'selectOrder', 'size' => 40)) }}                     
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 required">          
						{{ Form::label('selectMessage', 'Message') }}   
						@if ($errors->has('message'))
							<p class="text-danger">{{ $errors->first('message') }}</p>
						@endif      
						{{ Form::text('message', old('message'), array('class'=>'form-control', 'id' => 'selectMessage', 'size' => 40)) }}                     
					</div>
				</div>
			</div>

			<div class="panel-footer">
				{{ Form::button('Save&nbsp;<i class="icon-arrow-right"></i>',['type' => 'submit', 'class' => 'btn btn-danger btn_click', 'id' => 'save']) }}
			</div>
		</div>


	</div>
</div>
{{ Form::close() }}



@stop

resources/views/modules/announcement/index.blade.php
@extends('layouts/backend')

@section('content')




{{ Form::open(array('class' => 'form-horizontal', 'id' => 'form-search')) }}             
<div class="row">
	<div class="col-md-12">
		<div class="well">
			<div class="row">
				<div class="col-md-12">

					<div class="row">
						<div class="col-md-3">
							{{ Form::select('type_id', $types, $sessions['type_id'], array('class' => 'form-control')) }}
						</div>
						<div class="col-md-3">
							{{ Form::select('status_id', $status, $sessions['status_id'], array('class' => 'form-control')) }}
						</div>                  						
						<div class="col-md-6">{{ Form::text('keyword', $sessions['keyword'], array('class'=>'form-control', 'placeholder' => 'Message')) }}
						</div>
					</div> 

					<br>    
					{{ Form::button('Search', array('class' => 'btn btn-warning', 'type' => 'submit', 'name' => 'btn-search')) }}
				</div>          
			</div>
		</div>
	</div>            
</div>
{{ Form::close() }}





<div class="row">
	<div class="col-sm-12">
		<table class="table table-striped table-condensed table-responsive table-bordered">
			<thead>
				<tr class="active">
					<th class="col-md-1">No</th>
					<th class="col-md-8">Message / Group</th>
					<th class="text-left col-md-1">Status</th>                 
					<th class="text-left col-md-1">Order</th>                 
					<th class="text-right col-md-1">Actions</th>                
				</tr>
			</thead>

			<tbody>
				@if (count($anno) > 0)
					<?php $no = $anno->firstItem() - 1;?>				
					@foreach ($anno as $i)
						<?php $no++; ?>
						<tr>
							<td>
								{{ $no }}
							</td>

							<td>
								{{ $i->message }} /<br>{!! $i->type_name !!}
							</td>
							<td>
								{!! $i->availability !!}
							</td>

							<td class="text-left">
								{{ Form::text('order', $i->order, array('class'=>'form-control', 'size' => 1, 'vertical-align' => 'center')) }}  
							</td>

							<td class="text-right">
								<a href="{{ route('mod.announcement.view', array($i->id)) }}" class="btn btn-primary btn-sm" title="View Detail"><i class="icon-magnifier-add"></i></a>
							</td>
						</tr>
					@endforeach
				@else
					<tr>
						<td colspan="5">No record</td>
					</tr>
				@endif
			</tbody>
		</table>

		<div class="well">
			<div class="paging text-center">  
				{{ $anno->render() }}      
				<p>{{ 'Total: '.$anno->total() }}</p>
			</div>
		</div>


	</div>
</div>


@stop

resources/views/modules/announcement/view.blade.php
@extends('layouts/backend')

@section('content')



{{ Form::open(array('class' => 'form-horizontal', 'id' => 'form-list')) }}
<div class="panel panel-primary">
	<div class="panel-body">

		<div class="row">
			<div class="col-md-12">	
				<table class="table table-condensed table-responsive table-hover table-striped">
					<thead>
						<tr class="bg-primary">
							<td colspan="2"><strong>Announcement Info</strong></td>
						</tr>
					</thead>
					<tr>
						<td class="col-md-3">Apply Date</td>
						<td class="col-md-9">{{ $detail->apply_date }}</td>
					</tr>
					<tr>
						<td>Created By</td>
						<td>
							@if (!empty($detail->CreatedBy))
								{{ $detail->CreatedBy->name }}
							@else
								{{ '-' }}
							@endif
						</td>
					</tr>
					<tr>
						<td>Message</td>
						<td>{{ $detail->message }}</td>
					</tr>
					<tr>
						<td>Type</td>
						<td>{!! $detail->type_name !!}</td>
					</tr>
					<tr>
						<td>Order</td>
						<td>{{ $detail->order }}</td>
					</tr>
					<tr>
						<td>Status</td>
						<td>{!! $detail->availability !!}</td>
					</tr>
				</table>
			</div>
		</div>
	</div>

	<div class="panel-footer">
		{{ Form::button('<i class="icon-close"></i>&nbsp;Cancel', array('class' => 'btn btn-danger btn_click', 'id' => 'cancel', 'title' => 'Cancel')) }}
	</div>

</div>
{{ Form::close() }}





@stop