app/Http/routes.php
<?php

use Illuminate\Support\Facades\Redis;

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
 */

// initial page
Route::get('/', 'Auth\AuthController@showLoginForm');

// authentication page
Route::auth();

// view home
Route::get('/home', [
    'as' => 'home',
    'uses' => 'HomeController@showHome',
]);

Route::get('message', [
    'as' => 'message',
    'uses' => 'HomeController@showMessage',
]);

Route::get('info/decompose','\Lubusin\Decomposer\Controllers\DecomposerController@index');

Route::get('info/logs', '\Rap2hpoutre\LaravelLogViewer\LogViewerController@index');

app/Models/WorkHour.php
<?php

namespace IhrV2\Models;

use Illuminate\Database\Eloquent\Model;
use IhrV2\Contracts\Maintenance\MaintenanceInterface;

class WorkHour extends Model
{
    protected $table = 'work_hours';

    protected $fillable = [
    	'user_id',
    	'sitecode',
    	'contract_id',
        'date_from',
        'date_to',
    	'time_in',
    	'time_out',
        'days',
    	'reason',
        'partner',
    	'created_by',
    	'updated_by',
    	'status'
    ];

    // get staff info
    // --------------
    public function StaffInfo() {
        return $this->belongsTo('IhrV2\User', 'user_id');
    }

    // get site info
    // -------------
    public function SiteInfo() {
        return $this->belongsTo('IhrV2\Models\Site', 'sitecode', 'code');
    }

    // get created by detail
    // ---------------------
    public function UserActionBy() {
        return $this->belongsTo('IhrV2\User', 'created_by');
    }

    // get contract info
    // -----------------
    public function ContractInfo() {
        return $this->belongsTo('IhrV2\Models\UserContract', 'contract_id');
    }

    // get off dates
    // -------------
    public function OffDates()
    {
        return $this->hasMany('IhrV2\Models\WorkHourOffDate', 'work_hour_id')->where('status', 1)->orderBy('off_date', 'asc');
    }

    // work hour attachment
    // --------------------
    public function TheAttachment() {
        return $this->hasOne('IhrV2\Models\WorkHourAttachment', 'work_hour_id')->where('status', 1);
    }

    // get status name
    // ---------------
    public function getAvailAttribute() {
        if ($this->status == 1) {
            return '<span class="text-primary">ACTIVE</span>';
        } else {
            return '<span class="text-danger">INACTIVE</span>';
        }
    }

    // get partner status
    // ------------------
    public function getPartnerStatusAttribute() {
        if ($this->partner != 0) {
            return '<span class="text-primary">YES</span>';
        } else {
            return '<span class="text-danger">NO</span>';
        }
    }

    // get name of day to be off
    // -------------------------
    public function getDayNameAttribute() {
        $exp = explode(':', $this->days);
        $days = \IhrV2\Models\Day::whereIn('id', $exp)->get();
        return $days;
    }



}

app/User.php
<?php

namespace IhrV2;

use Hash;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Tymon\JWTAuth\Contracts\JWTSubject;

// use Illuminate\Database\Eloquent\Model;

class User extends Authenticatable {
    
    // public $timestamps = false;

    protected $table = 'users';

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */

    protected $fillable = [
        'username',
        'name',
        'staff_id',
        'prev_staff_id',
        'email',
        'password',
        'api_token',
        'group_id',
        'is_admin',
        'icno',
        'permanent_street_1',
        'permanent_street_2',
        'permanent_postcode',
        'permanent_city',
        'permanent_state',
        'correspondence_street_1',
        'correspondence_street_2',
        'correspondence_postcode',
        'correspondence_city',
        'correspondence_state',
        'telno1',
        'telno2',
        'hpno',
        'hpno2',
        'faxno',
        'website',
        'personal_email',
        'work_email',
        'gender_id',
        'marital_id',
        'height',
        'weight',
        'dob',
        'pob',
        'nationality_id',
        'race_id',
        'religion_id',
        'partner_name',
        'partner_phone',
        'child_no',
        'sitecode',
        'itaxno',
        'epfno',
        'socsono',
        'bankname',
        'bankno',
        'status',
        'remember_token',
        'sid',
        'action_date',
        'last_login',
        'date_created',
        'date_modified',
        'imei',
        'device',
        'edit',
        'mobile',
        'created_at',
        'updated_at'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    protected $hidden = [
        'password', 'remember_token', 'api_token'
    ];

    // public function roles()
    // {
    //     return $this->belongsToMany(Role::class);
    // }

    // public function hasRole($role) //
    // {
    //     if (is_string($role)) {
    //         return $this->roles->contains('name', $role);
    //     }
    //     return !! $role->intersect($this->roles)->count();
    // }

    // public function assign($role)
    // {
    //     if (is_string($role)) {
    //         return $this->roles()->save(
    //             Role::whereName($role)->firstOrFail()
    //         );
    //     }
    //     return $this->roles()->save($role);
    // }

    /**
     * Always hash the password when we save it to the database
     */
    // public function setPasswordAttribute($value) {
    //     $this->attributes['password'] = Hash::make($value);
    // }

    // always encrypt value password when user enter the password
    // public function setPasswordAttribute($value)
    // {
    //     $this->attributes['password'] = bcrypt($value);
    // }

    public function getEmailForPasswordReset() {
        return $this->personal_email;
    }

    public function scopeIsActive($q) {
        $q->where('status', 1);
    }

    public function scopeIsActiveAndIDDesc($q) {
        $q->where('status', 1)->orderBy('id', 'DESC');
    }

    // belongs to
    // ----------
    public function GroupName() {
        return $this->belongsTo('IhrV2\Models\Group', 'group_id');
    }

    public function GenderName() {
        return $this->belongsTo('IhrV2\Models\Gender', 'gender_id');
    }

    public function MaritalName() {
        return $this->belongsTo('IhrV2\Models\MaritalStatus', 'marital_id');
    }

    public function RaceName() {
        return $this->belongsTo('IhrV2\Models\Race', 'race_id');
    }

    public function ReligionName() {
        return $this->belongsTo('IhrV2\Models\Religion', 'religion_id');
    }

    public function NationalityName() {
        return $this->belongsTo('IhrV2\Models\Nationality', 'nationality_id');
    }

    public function SiteNameInfo() {
        return $this->belongsTo('IhrV2\Models\Site', 'sitecode', 'code');
    }

    public function StatusName() {
        return $this->belongsTo('IhrV2\Models\UserStatus', 'status');
    }

    // has one
    // -------
    public function UserLatestJob() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLatestJob2() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 1);
    }

    public function UserCurrentJob() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->orderBy('id', 'desc');
    }

    public function UserCurrentJob2() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('flag', 1);
    }

    public function UserCurrentContract2() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('flag', 1);
    }    

    public function UserLatestContract() {
        // return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1);
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLatestContract2() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 1)->where('flag', 1);
    }

    public function UserLastContract() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->orderBy('id', 'desc');
    }

    public function UserInactive() {
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2);
    }

    // inactive job & contract
    // -----------------------
    public function UserInactiveJob() {
        // return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2);
        return $this->hasOne('IhrV2\Models\UserJob', 'user_id')->where('status', 2)->where('flag', 1);
    }

    public function UserInactiveContract() {
        return $this->hasOne('IhrV2\Models\UserContract', 'user_id')->where('status', 2)->where('flag', 1);
    }

    // user photo
    // ----------
    public function UserPhotoActive() {
        return $this->hasOne('IhrV2\Models\UserPhoto', 'user_id')->where('active', 1);
    }

    public function UserPhotoApproved() {
        return $this->hasOne('IhrV2\Models\UserPhotoHistory', 'user_id')->where('status', 2)->where('flag', 1);
    }

    // has many
    // --------
    public function UserJob() {
        return $this->hasMany('IhrV2\Models\UserJob', 'user_id');
    }

    public function UserContract() {
        return $this->hasMany('IhrV2\Models\UserContract', 'user_id');
    }

    public function UserEducation() {
        return $this->hasMany('IhrV2\Models\UserEducation', 'user_id')->orderBy('id', 'DESC');
    }

    public function UserEducationOne() {
        return $this->hasOne('IhrV2\Models\UserEducation', 'user_id')->orderBy('id', 'DESC');
    }

    public function UserEmergency() {
        return $this->hasMany('IhrV2\Models\UserEmergency', 'user_id')->orderBy('id', 'DESC');
    }

    // display status color
    // --------------------
    public function getStatusColorAttribute() {
        if ($this->status == 1) {
            return '<span class="text-primary">' . strtoupper($this->StatusName->name) . '</span>';
        } else {
            return '<span class="text-danger">' . strtoupper($this->StatusName->name) . '</span>';
        }
    }

}

resources/views/modules/leave/user/work-hour/view.blade.php
@extends('layouts/backend')

@section('content')

<script type="text/javascript" src="{{ asset('assets/js/bootstrap-datetimepicker.js') }}"></script>
<link href="{{ asset('/assets/css.old/bootstrap-datetimepicker.css') }}" rel="stylesheet">




<div class="row">
	<div class="col-md-12">
		<table class="table table-striped table-condensed table-responsive table-hover">
			<thead>
				<tr class="bg-inverse">
					<th class="col-md-1">No</th>
					<th class="col-md-2 text-left">Contract Date</th>
					<th class="col-md-2 text-center">Time In</th>
					<th class="col-md-2 text-center">Time Out</th>
					<th class="col-md-2 text-left">Off Day</th>
					<th class="col-md-1 text-center">Status</th>
					<th class="col-md-1 text-center"><i class="icon-picture" title="Attachment"></i></th>
					<th class="col-md-1 text-right">Actions</th>
				</tr>
			</thead>
			<tbody>
				@if (count($work_hour) > 0)
					<?php $no = 0; ?>
					@foreach ($work_hour as $i)
						<?php $no++; ?>
						<tr>
							<td>{{ $no }}</td>
							<td class="text-left">
								{{ \Carbon\Carbon::parse($i->ContractInfo->date_from)->format('j M Y') }} - {{ \Carbon\Carbon::parse($i->ContractInfo->date_to)->format('j M Y') }}
							</td>
							<td class="text-center">{{ $i->time_in }}</td>
							<td class="text-center">{{ $i->time_out }}</td>
							<td>
								@foreach ($i->day_name as $d)
									{{ $d->name }}<br>
								@endforeach
							</td>
							<td class="text-center">{!! $i->avail !!}</td>
							<td class="text-center">							
								@if ($i->TheAttachment)
									<?php
										$attachment = $i->TheAttachment->filename . '.' . $i->TheAttachment->ext;
										$photo = route('lib.file.misc', array($attachment));
									?>
									<a href="{{ $photo }}" target="_blank"><i class="icon-paper-clip"></i></a>
								@else
									{{ '-' }}
								@endif
							</td>
							<td class="text-right">
								<a href="#" id="modal-popup" data-url="{{ route('mod.leave.user.work-hour.view.popup', array($i->id, $i->user_id, $i->sitecode)) }}" class="btn btn-success btn-sm" title="View Details"><i class="icon-magnifier-add"></i></a>
							</td>
						</tr>
					@endforeach
				@else
					<tr><td colspan="8">No record</td></tr>
				@endif

			</tbody>
		</table>
	</div>
</div>



{{ Form::open(array('class' => 'form-horizontal', 'role' => 'form', 'files' => true)) }}
<div class="row">
	<div class="col-lg-12">

		<div class="panel panel-default">
			<div class="panel-body">
				<legend>Work Hour Info</legend>

				<div class="form-group">
					<div class="col-md-3 required">
						{{ Form::label('Contract') }}
						@if ($errors->has('contract_id'))
							<p class="text-danger">{{ $errors->first('contract_id') }}</p>
						@endif
						{{ Form::select('contract_id', $contracts, old('contract_id'), array('class' => 'form-control')) }}
					</div>
				</div>


				<div class="form-group">
					<div class="col-md-3 required">
						{{ Form::label('Time In') }}
						@if ($errors->has('time_in'))
							<p class="text-danger">{{ $errors->first('time_in') }}</p>
						@endif
						<div class="input-group date" id="pick_time_in">
							{{ Form::text('time_in', old('time_in'), array('class' => 'form-control', 'data-date-format' => 'HH:mm', 'readonly')) }}
							<span class="input-group-addon"><i class="icon-calendar"></i>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-3 required">
						{{ Form::label('Time Out') }}
						@if ($errors->has('time_out'))
							<p class="text-danger">{{ $errors->first('time_out') }}</p>
						@endif
						<div class="input-group date" id="pick_time_out">
							{{ Form::text('time_out', old('time_out'), array('class' => 'form-control', 'data-date-format' => 'HH:mm', 'readonly')) }}
							<span class="input-group-addon"><i class="icon-calendar"></i>
						</div>
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-3 required">
						{{ Form::label('Off Day (Every Week)') }}
						@if ($errors->has('day'))
							<p class="text-danger">{{ $errors->first('day') }}</p>
						@endif						
						@if (!empty($days))
							@foreach ($days as $d)
								<br>{{ Form::checkbox('day[]', $d['id'], null, ['class' => 'check-day']) }}&nbsp;{{ $d['name'] }}
							@endforeach
						@else

						@endif
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4 required">
						{{ Form::label('Reason') }}
						@if ($errors->has('reason'))
							<p class="text-danger">{{ $errors->first('reason') }}</p>
						@endif
						{{ Form::textarea('reason', old('reason'), ['class' => 'form-control', 'size' => '30x3']) }}
					</div>
				</div>

				<div class="form-group">
					<div class="col-md-4">
						{{ Form::label('Has M/AM') }}
						@if ($errors->has('partner'))
							<p class="text-danger">{{ $errors->first('partner') }}</p>
						@endif
						{{ Form::checkbox('partner', 1) }}
					</div>
				</div>



                <div class="form-group">
                    <div class="col-md-6 required">
                        {{ Form::label('Attachment') }}
                        @if ($errors->has('file'))
                            <p class="text-danger">{{ $errors->first('file') }}</p>
                        @endif
                        {{ Form::file('file') }}
                    </div>
                </div>

			</div>
            <div class="panel-footer">
                <div class="row">
                    <div class="col-md-6">
                        {{ Form::button('Save&nbsp;<i class="icon-arrow-right"></i>',['type' => 'button', 'class' => 'btn btn-danger btn_click', 'id' => 'save']) }}
                    </div>
                </div>
            </div>


		</div>
	</div>
</div>




{{ Form::close() }}



<script type="text/javascript">
$(function () {
	getTimePicker('pick_time_in');
	getTimePicker('pick_time_out');
});
</script>





@stop